[[allowlist]]
  description = "Allow specific secret files as they are not secrets that matter."

  paths = [
    "components/platform/users/files/users.htpasswd",
    "components/platform/users/base/htpass-secret.yaml",
    "components/apps/keycloak/base/admin-secret.yaml"
  ]
