apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - acme-inc-model-1-llm-inference.yaml
  - serverless-model-1-llm-inference.yaml
  - serverless-model-2-llm-inference.yaml
